# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{by_star}
  s.version = "0.5.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ryan Bigg", "Mislav Marohni\304\207"]
  s.date = %q{2009-11-15}
  s.description = %q{ActiveRecord extension for easier date scopes and time ranges}
  s.email = %q{radarlistener@gmail.com}
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    ".gitignore",
     "MIT-LICENSE",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "by_star.gemspec",
     "lib/by_star.rb",
     "lib/calculations.rb",
     "lib/calculations/count.rb",
     "lib/calculations/sum.rb",
     "lib/range_calculations.rb",
     "lib/shared.rb",
     "lib/time_ext.rb",
     "lib/vanilla.rb",
     "rails/init.rb",
     "spec/by_star_spec.rb",
     "spec/database.yml",
     "spec/fixtures/models.rb",
     "spec/fixtures/schema.rb",
     "spec/spec_helper.rb",
     "tmp/.gitignore"
  ]
  s.homepage = %q{http://github.com/radar/by_star}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{ActiveRecord extension for easier date scopes and time ranges}
  s.test_files = [
    "spec/by_star_spec.rb",
     "spec/fixtures/models.rb",
     "spec/fixtures/schema.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 0"])
  end
end
