sqlite:
  adapter: sqlite3
  database: by_star.sqlite3

postgres:
  adapter: postgresql
  database: by_star_test
  username: postgres
  min_messages: warning

mysql:
  adapter: mysql2
  database: by_star_test
  username: root
  encoding: utf8
