name: PostgreSQL tests

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  postgresql:
    strategy:
      fail-fast: false
      matrix:
        ruby_version: [3.2, 3.1, 3.0, 2.7]
        gemfile:
          [
            spec/gemfiles/Gemfile.rails60,
            spec/gemfiles/Gemfile.rails61,
            spec/gemfiles/Gemfile.rails70,
            spec/gemfiles/Gemfile.rails,
          ]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@master
        with:
          ruby-version: ${{ matrix.ruby_version }}

      - uses: harmon758/postgresql-action@v1
        with:
          postgresql version: '11'

      - name: Start PostgreSQL
        run: |
          sudo service postgresql start
          sudo -u postgres createuser --superuser "$USER"
          createdb by_star_test

      - name: Build and test with Rake
        env:
          BUNDLE_GEMFILE: ${{ matrix.gemfile }}
          DB: "postgres"
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec rake
